server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personnel?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage: wang.doug.frame.model
  mapperLocations: classpath:mapper/*.xml
